# Livy Configuration

# Server
livy.server.host = 0.0.0.0
livy.server.port = 8998
livy.server.session.timeout = 2h

# Spark
livy.spark.master = local[*]
livy.spark.deploy-mode = client

# Disable event logging to avoid HDFS requirement
livy.spark.eventLog.enabled = false

# File upload
livy.file.local-dir-whitelist = /tmp
livy.repl.enable-hive-context = false

# RSC
livy.rsc.launcher.port.range = 10000~10010
